name: Trigger Umbrella Repo Update

on:
  push:
    branches: [master, main]
  release:
    types: [published]

jobs:
  trigger-umbrella-update:
    name: Trigger Umbrella Repo Update
    runs-on: ubuntu-latest
    
    steps:
      - name: Format commit message
        id: format-commit
        run: |
          # Get first line of commit message (title only)
          COMMIT_TITLE=$(echo '${{ github.event.head_commit.message }}' | head -n1 | tr -d '\n\r')
          # Limit to 80 characters and remove problematic characters
          CLEAN_TITLE=$(echo "$COMMIT_TITLE" | cut -c1-80 | sed 's/[[:cntrl:]]//g')
          echo "title=$CLEAN_TITLE" >> $GITHUB_OUTPUT
          echo "short_sha=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT

      - name: Trigger umbrella repo submodule update
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.UMBRELLA_REPO_TOKEN }}
          repository: zachatkinson/csfrace-scrape
          event-type: frontend-updated
          client-payload: |
            {
              "repository": "${{ github.repository }}",
              "ref": "${{ github.ref }}",
              "sha": "${{ github.sha }}",
              "short_sha": "${{ steps.format-commit.outputs.short_sha }}",
              "actor": "${{ github.actor }}",
              "workflow": "${{ github.workflow }}",
              "timestamp": "${{ github.event.head_commit.timestamp }}",
              "message": "${{ steps.format-commit.outputs.title }}",
              "url": "${{ github.event.head_commit.url }}"
            }

      - name: Log trigger event
        run: |
          echo "🚀 Triggered umbrella repo update for frontend"
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
          echo "Message: ${{ github.event.head_commit.message }}"